color: null
description: null
fieldLayouts:
  ee8cb276-2f5a-4993-b75a-f19b5ebe6079:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-26T18:39:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6356f107-316c-4b3b-894f-c6ba2d253c09
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-26T18:44:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 46692f35-2d90-4c5a-881a-b12fe38261bb # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63c216e0-3c2b-4bc7-b512-97c7a55d5001
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-26T18:45:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9c9c7c3f-641a-4caa-bd0c-80b8b84cb038 # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8c70552-ea70-44cf-9726-62e5c649f59e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-07T20:09:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 052ec829-cd89-4e73-9d37-e3c1c3716d98 # Page Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0509e008-b5c6-4844-89a1-2a7feb99f166
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-07T18:16:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 29b25fd9-e453-40f9-86b8-6d28a75104f2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1b16fea-5001-4888-a1f8-0234371e6f7c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cca4db25-5c7c-43ae-9207-db1d4c438a7f
        userCondition: null
handle: product
hasTitleField: true
icon: null
name: Product
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
