columnSuffix: null
handle: optimizedCard
instructions: null
name: 'Optimized Card'
searchable: false
settings:
  displayDominantColorPalette: true
  displayLazyLoadPlaceholderImages: true
  displayOptimizedImageVariants: true
  fieldVolumeSettings:
    __assoc__:
      -
        - images
        - '*'
  ignoreFilesOfType:
    - image/svg
    - image/gif
    - application/pdf
  variants:
    -
      __assoc__:
        -
          - width
          - '640'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '8'
        -
          - aspectRatioY
          - '5'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
