dateModified: 1772831887
email:
  fromEmail: admin@example.com
  fromName: 'Jeffs Amish Furniture'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  catalogs:
    hasUrls: true
    name: Catalogs
    settings:
      path: '@webroot/catalogs'
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL/catalogs
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/assets/images'
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL/assets/images
meta:
  __names__:
    1d0f4b2d-71ec-46fd-be3d-ae1d063e7da5: Section # Section
    3c4fa3a1-3471-41b1-a0bd-92d1b1611553: 'Jeffs Amish Furniture' # Jeffs Amish Furniture
    3ec41d95-2d59-45ff-a62f-23803f31acfc: Product # Product
    5ac24545-f7d7-4723-becb-6e2728256162: 'Products Index' # Products Index
    07b93a57-d74c-458a-bb95-f5bffa4e6b7b: Image # Image
    9c9c7c3f-641a-4caa-bd0c-80b8b84cb038: Summary # Summary
    009c864c-69df-4137-aaf0-c7c9aa94e5a9: Text # Text
    9d93bd96-bdd3-45ef-9cbc-bd10f7e614c6: 'Catalog Link' # Catalog Link
    052ec829-cd89-4e73-9d37-e3c1c3716d98: 'Page Builder' # Page Builder
    54cc2d09-8e13-4b06-ae04-d2d04ad2b962: 'Contact Us' # Contact Us
    554e1d91-27c8-406c-93f4-7d8b0053103c: Body # Body
    1074ed63-9cf0-42d1-bb9d-d73f1d0fac32: Catalog # Catalog
    9879dccc-a097-4855-aa3e-e8973ac227a1: Image # Image
    46692f35-2d90-4c5a-881a-b12fe38261bb: 'Featured Image' # Featured Image
    57448539-5980-4f7e-a2f8-f618d7d5a8d1: 'Public Schema' # Public Schema
    c5199e9a-4c8e-4613-b710-b4e0ba44e04b: 'Optimized Hero' # Optimized Hero
    d4a0c17c-c177-4c51-b9c1-db9ed5b3cab8: 'Jeffs Amish Furniture' # Jeffs Amish Furniture
    d8e1fff6-4856-4995-baa0-63cd11e269d0: Images # Images
    d524211a-0921-4e1c-b85c-53439c75de38: About # About
    e761d798-e850-4460-a152-68eaccb00dfc: Catalogs # Catalogs
    eb4751bc-b634-4972-b531-ee04ca79a67b: 'Optimized Card' # Optimized Card
    f8b59243-10a7-4ff8-aff0-0894166c1489: 'Page Content' # Page Content
    fa06da39-f6a6-4333-92f9-8f9083d89327: 'Furniture Section' # Furniture Section
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 5.0.0.1
  cp-clearcache:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  freeform:
    edition: pro
    enabled: true
    licenseKey: ZJQMO7J4Y9J8MO2IAFXVHM0H
    schemaVersion: 5.14.3
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: P8WTVZQK6T6DKNILEA5CJIK3
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Jeffs Amish Furniture'
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
