defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f8b59243-10a7-4ff8-aff0-0894166c1489 # Page Content
handle: productsIndex
maxAuthors: 1
name: 'Products Index'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3c4fa3a1-3471-41b1-a0bd-92d1b1611553: # Jeffs Amish Furniture
    enabledByDefault: true
    hasUrls: true
    template: products/index.twig
    uriFormat: products
type: single
