defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3ec41d95-2d59-45ff-a62f-23803f31acfc # Product
handle: products
maxAuthors: 1
name: Products
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  3c4fa3a1-3471-41b1-a0bd-92d1b1611553: # Jeffs Amish Furniture
    enabledByDefault: true
    hasUrls: true
    template: products/_entry.twig
    uriFormat: 'products/{slug}'
structure:
  maxLevels: null
  uid: 53c8f13c-0ec6-462a-8f90-b3f6eba64125
type: structure
